BEGIN;

	CREATE TABLE FRIENDSHIP (

		F_FRIENDSHIPKEY		SERIAL PRIMARY KEY,
		F_FIRSTCUSTKEY		BIGINT NOT NULL,  -- references C_CUSTKEY
		F_SECONDCUSTKEY		BIGINT NOT NULL  -- references C_CUSTKEY
	);

	COPY friendship FROM '/home/robert/Code/ZBD/6/result.csv' WITH (FORMAT csv, DELIMITER '|');

COMMIT;

ALTER TABLE FRIENDSHIP ADD FOREIGN KEY (F_FIRSTCUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);

ALTER TABLE FRIENDSHIP ADD FOREIGN KEY (F_SECONDCUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);
